### ISSUE TITLE
Only controls one of the GPU fans

### ISSUE THREAD

**Issue by kelderek** [mikejzx/linux-nvidia-fan-curve#2]
My GPU has 2 fans, and your utility works wonderfully except that it only controls one of the fans, leaving the other to hardware fan curve.  I have created a pull request to specify all fans on  GPU-0: #1

**Comment by mikejzx** [comment]
@kelderek 

Thanks for your contributions!  I was honestly shocked when I saw them, and had to chuckle at it; I never thought that anybody would actually use or modify this dodgy little program I wrote a few years ago.

I'll just have to assume that the program still works fine with your modifications as these days I'm running an AMD card and no longer use this utility. :wink:

**Comment by kelderek** [comment]
My pleasure, thanks for writing the program!  I was wondering if you would ever even see my PRs haha

I am working my way from Windows to Linux (Kubuntu) on my home computer, and with Proton, even gaming is very doable.  The only thing I was missing was something to edit the fan curve because the stock curve on my card isn't good and keeping going into hyperdrive for a couple seconds, then, back to probably 80%, then back to hyperdrive, and so on, which is super frustrating.  Much nicer to set it to just be 90% or even 100% constantly than have it constantly cycling.

There are nice heavyweight GUI programs like GWE that let you overclock and stuff too, but I liked your script because it small, simple, and invisible.  I already knew the curve I wanted from Windows so this was perfect, I can just set it and forget it.  The only issue was that I needed it to control both fans on my card which was an easy enough tweak.  The second PR was just a fun exercise for me.

The changes I made are pretty straightforward so I have a high degree of confidence they should work just as well for others as they do for me.  Maybe someone else will come along and try it out! :)
